name: BuySkills
main: de.craftlancer.buyskills.BuySkills
version: Beta1
author: SydMontague
dev-url: http://dev.bukkit.org/server-mods/expskills/
description: Buy permission nodes and groups with money, and other currencies!
depend: [Vault, CurrencyHandler]
commands:
    skill:
        description: Gives out XP and current Level    
        usage: |
            /skill help [command] - get help for this plugin
            /skill list <page> <filter> - list available skills
            /skill info <skill> - get information to a specific skill
            /skill buy <skill> - buy a skill
            /skill rent <skill> <time> - rent a skill
            /skill current - show your bought skills
            /skill rented - show's your rented skills
permissions:
    buyskills.command.help:
        description: Grant access to /help command
        default: false
    buyskills.command.list:
        description: Grant access to /list command
        default: false
    buyskills.command.info:
        description: Grant access to /info command
        default: false
    buyskills.command.buy:
        description: Grant access to /buy command
        default: false
    buyskills.command.rent:
        description: Grant access to /rent command
        default: false
    buyskills.command.current:
        description: Grant access to /current command
        default: false
    buyskills.command.rented:
        description: Grant access to /rented command
        default: false
    buyskills.command.recalculate:
        description: Grant access to /recalculate command
        default: false
    buyskills.command.reload:
        description: Grant access to /reload command
        default: false
    buyskills.command.reset:  
        description: Grant access to /reset command
        default: false
    buyskills.command.revoke:
        description: Grant access to /revoke command
        default: false
    buyskills.command.grant:
        description: Grant access to /grant command
        default: false
    buyskills.user:
        default: false
        children:
            buyskills.command.help: true
            buyskills.command.list: true
            buyskills.command.info: true
            buyskills.command.buy: true
            buyskills.command.rent: true
            buyskills.command.current: true
            buyskills.command.rented: true
    buyskills.admin:
        default: false
        children:
            buyskills.command.recalculate: true
            buyskills.command.reload: true
            buyskills.command.reset: true
            buyskills.command.revoke: true
            buyskills.command.grant: true