name: ExpSkills
main: com.syd.expskills.ExpSkills
version: 0.9_beta3
description: Buy Skills with XP, money and more!
softdepend: [Vault, Register]
commands:
    exp:
        description: Gives out XP and current Level    
        usage: |
            /exp help [command] - get help for this plugin
            /exp stats - show your stats
            /exp list <page> <filter> - list available skills
            /exp info <skill> - get information to a specific skill
            /exp buy <skill> - buy a skill
            /exp rent <skill> <time> - rent a skill
            /exp current - show your bought skills
            /exp rented - show's your rented skills
        aliases: [skills, skill]
permissions:
  expskills.use:
    description: Use ExpSkills
    default: true
  expskills.admin:
    description: Use Admin Commands
    default: op