name: ExpSkills
main: com.syd.expskills.ExpSkills
version: 0.8.4_beta2
author: SydMontague
dev-url: http://dev.bukkit.org/server-mods/expskills/
description: Buy Skills with XP, money and more!
softdepend: [Vault, Register]
commands:
    exp:
        description: Gives out XP and current Level    
        usage: |
            /exp help [command] - get help for this plugin
            /exp stats - show your stats
            /exp list <page> <filter> - list available skills
            /exp info <skill> - get information to a specific skill
            /exp buy <skill> - buy a skill
            /exp rent <skill> <time> - rent a skill
            /exp current - show your bought skills
            /exp rented - show's your rented skills
        aliases: [skills, skill]
permissions:
  expskills.use:
    description: Use ExpSkills
    default: false
  expskills.admin:
    description: Use all admin Commands
    default: op
  expskills.current.others:
    description: Get bought skills of other players
    default: false
  expskills.rented.others:
    description: Get rented skills of other players
    default: false
  expskills.admin.add:
    description: Add skillpoints/XP/level
    default: false
  expskills.admin.set:
    description: Set skillpoints/XP/level
    default: false
  expskills.admin.reset:
    description: reset skills
    default: false
  expskills.admin.grant:
    description: Grant a skill
    default: false
  expskills.admin.revoke:
    description: Revoke a skill
    default: false
    